apiVersion: batch/v1
kind: Job
metadata: 
   name: backup-job
spec:
  template:
    metadata: 
       name: backup
    spec:
      restartPolicy: Never

      containers:
        - name: backup-cont
          image: mysql:5.7
          command:
              - "bash"
              - "-c"
              - |
                echo "database $MYSQL_DATABASE $MYSQL_USER $MYSQL_PASSWORD "
                mysqldump -h mysql-service -u root -pamir --all-databases  > /var/lib/backup/mysql-backup$(date +%e-%m-%G).sql
                
                if [[ $? == 0  ]]; then
                   echo "backup mysql-backup$(date +%e-%m-%G).sql  is taken successfully in minikube /home/minikube/mountBackups"
                else
                   echo "backup is failed.."
                fi 

          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
            - name: mysql-backup
              mountPath: /var/lib/backup 
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                    name: wiki-vars
                    key: DB_NAME

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                   name: wiki-secrets
                   key: DB_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                 secretKeyRef:
                     name: wiki-secrets
                     key: DB_PASS
                                   #value: amir
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                 secretKeyRef:
                    name: wiki-secrets
                    key: DB_PASS
      
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
             claimName:  mysql-pvc

        - name: mysql-backup
          hostPath:
            path: /home/minikube/mountBackups

          #          persistentVolumeClaim:
          #             claimName: mysql-backup-pvc      
