apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels: 
     pv: mysql
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: standard

  persistentVolumeReclaimPolicy: Retain
  hostPath:
     path: /mnt/mysql-data


