apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backup-pv
  labels:
     pv: mysql-backup
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: standard

  persistentVolumeReclaimPolicy: Retain

  nfs:
    server: 192.168.1.2
    path: /srv/nfs/shared/

